name: flutter_language_detect
description: A Flutter package for detecting the language of a given text using character-wise n-gram models
version: 0.0.1
homepage: https://github.com/leetuanbmt/flutter_language_detect
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: "^3.29.3"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
